
server:
  port: 9090

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.zchzh.democonsumer
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 30000
spring:
  application:
    name: consumer